name: Run tests and coverage

on: [push]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout Pycollo
        uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: test-environment
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          conda-build-version: 3.21.4
      - name: Install basic dependencies
        run: conda install -q -y --file=requirements.txt --file=tests/requirements.txt --file=docs/requirements.txt
      - name: Install Pycollo
        run: python setup.py install
      - name: Test with pytest
        run: pytest tests/
      - name: Build dummy documentation
        run: |
          cd docs; make clean; cd ..
          sphinx-build -nWT -b dummy docs/source docs/build